// Capture listing layouts around screenshots of the real popup (no invented UI).
const {chromium}=require('playwright');
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'store/assets');
const data=name=>'data:image/png;base64,'+fs.readFileSync(path.join(OUT,name)).toString('base64');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_BIN,headless:true,args:['--no-sandbox','--disable-gpu']});const p=await b.newPage();
const slides=[
 ['01-control.png','YOUR FEED. YOUR RULES.','Less noise.\nMore choice.','Filter AI topics, unwanted phrases\nand creators on Facebook and YouTube.','popup-en.png'],
 ['02-personal-rules.png','PERSONAL FILTERS','Choose what\nyou see.','Add topics and creator rules.\nKeep what matters with exceptions.','manage-en.png'],
 ['03-controls.png','LOCAL FILTERING','Tune the\ndetails.','Adjust AI coverage, metadata checks\nand blur strength in one compact panel.','advanced-en.png'],
 ['04-arabic.png','ENGLISH + ARABIC','A familiar\nway to filter.','Switch the popup language.\nKeep the same rules and controls.','popup-ar.png']
];
for(const [file,eyebrow,title,sub,img]of slides){await p.setViewportSize({width:1280,height:800});await p.setContent(`<html><head><style>*{box-sizing:border-box}body{margin:0;background:#0d0f12;color:#f7f8fb;font-family:Arial,sans-serif}.eyebrow{font-size:18px;font-weight:700;letter-spacing:3px;color:#7394ff}h1{font-size:76px;letter-spacing:-3px;line-height:1.04;margin:30px 0}p{font-size:25px;line-height:1.5;color:#a7adb8}.copy{position:absolute;left:70px;top:170px}.brand{position:absolute;left:70px;top:52px;font-size:23px;font-weight:700}.screen{position:absolute;right:100px;top:80px;width:418px;height:594px;object-fit:contain;box-shadow:0 25px 90px #000;border:1px solid #313842;border-radius:8px}.note{position:absolute;right:100px;top:696px;width:418px;text-align:center;font-size:14px;color:#8993a3}.line{position:absolute;left:70px;bottom:66px;font-size:16px;color:#8993a3}.bar{position:absolute;right:0;top:0;width:12px;height:800px;background:#3d6af2}</style></head><body><div class="brand">No AI Feed</div><div class="copy"><div class="eyebrow">${eyebrow}</div><h1>${title.replaceAll('\n','<br>')}</h1><p>${sub.replaceAll('\n','<br>')}</p></div><img class="screen" src="${data(img)}"><div class="note">Actual extension interface · Example filter rules</div><div class="line">Rule-based filtering. No external AI service.</div><div class="bar"></div></body></html>`);await p.screenshot({path:OUT+'/'+file});}
const icon='data:image/png;base64,'+fs.readFileSync(ROOT+'/icons/icon128.png').toString('base64');
for(const [w,h,file]of [[440,280,'promo-440x280.png'],[1400,560,'marquee-1400x560.png']]){await p.setViewportSize({width:w,height:h});const small=w===440;await p.setContent(`<html><style>*{box-sizing:border-box}body{margin:0;background:#3d6af2;color:white;font-family:Arial,sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;gap:${small?20:65}px}.icon{width:${small?96:160}px;height:${small?96:160}px;border-radius:24px}h1{font-size:${small?32:76}px;letter-spacing:-1.5px;margin:0 0 12px}p{font-size:${small?15:27}px;margin:0;line-height:1.45;color:#e0e7ff}</style><body><img class="icon" src="${icon}"><div><h1>No AI Feed</h1><p>Your feed, your rules.<br>Facebook + YouTube</p></div></body></html>`);await p.screenshot({path:OUT+'/'+file});}
fs.copyFileSync(ROOT+'/icons/icon128.png',OUT+'/store-icon-128.png');await b.close();console.log('4 listing screenshots, required promo tile, optional marquee, store icon');})();
