'use strict';

const CACHE_LIMIT = 400;
const MAX_SCAN_BYTES = 2 * 1024 * 1024;
const cache = new Map();

const SIGNALS = [
  {
    level: 1,
    confidence: 'very high',
    reason: 'Metadata marks this media as generated by AI',
    patterns: [
      /trainedAlgorithmicMedia/i,
      /digitalSourceType[^\x00]{0,160}(?:trainedAlgorithmicMedia|generative[- ]?ai)/i,
      /(?:created|generated)[^\x00]{0,80}(?:using|with|by)[^\x00]{0,50}(?:generative ai|artificial intelligence)/i
    ]
  },
  {
    level: 2,
    confidence: 'high',
    reason: 'Metadata identifies an AI generation tool',
    patterns: [
      /midjourney/i, /stable diffusion/i, /stability ai/i, /dall[- ]?e/i,
      /openai[^\x00]{0,60}(?:image|generator|sora)/i, /adobe firefly/i,
      /comfyui/i, /automatic1111/i, /fooocus/i, /leonardo ai/i,
      /ideogram/i, /runway[^\x00]{0,30}(?:gen|ml)/i, /kling ai/i,
      /luma dream machine/i, /flux(?:\.1)?[^\x00]{0,30}(?:ai|model|generator)/i
    ]
  },
  {
    level: 3,
    confidence: 'high',
    reason: 'Creator/software metadata indicates generative AI',
    patterns: [
      /(?:CreatorTool|Software|creator|generator|model)[^\x00]{0,100}(?:generative ai|ai generator|text[- ]to[- ]image|text[- ]to[- ]video|diffusion)/i,
      /(?:prompt|negative prompt|sampler|seed|steps|cfg scale)[^\x00]{0,140}(?:model|diffusion|checkpoint)/i
    ]
  },
  {
    level: 4,
    confidence: 'medium',
    reason: 'Metadata contains AI-generation provenance terms',
    patterns: [
      /generative[- ]?ai/i,
      /ai[- ]generated/i,
      /synthetic media/i,
      /text[- ]to[- ]image/i,
      /text[- ]to[- ]video/i,
      /diffusion model/i
    ]
  },
  {
    level: 5,
    confidence: 'low',
    reason: 'Metadata contains a broad AI-related marker',
    patterns: [
      /(?:CreatorTool|Software|Description|Comment|XMP)[^\x00]{0,120}\bAI\b/i,
      /(?:CreatorTool|Software|Description|Comment)[^\x00]{0,120}\b(?:ChatGPT|Claude|Gemini|Copilot)\b/i
    ]
  }
];

function remember(key, value) {
  cache.set(key, value);
  if (cache.size > CACHE_LIMIT) cache.delete(cache.keys().next().value);
}

function ascii(bytes) {
  let out = '';
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    out += String.fromCharCode(...bytes.subarray(i, Math.min(i + chunk, bytes.length)));
  }
  return out;
}

function u32be(view, offset) {
  if (offset + 4 > view.byteLength) return 0;
  return view.getUint32(offset, false);
}

function u32le(view, offset) {
  if (offset + 4 > view.byteLength) return 0;
  return view.getUint32(offset, true);
}

function metadataSegments(buffer, contentType = '') {
  const bytes = new Uint8Array(buffer);
  const view = new DataView(buffer);
  const chunks = [];

  // JPEG: scan metadata-bearing APP markers until the image scan begins.
  if (bytes[0] === 0xff && bytes[1] === 0xd8) {
    let p = 2;
    while (p + 4 <= bytes.length) {
      if (bytes[p] !== 0xff) { p += 1; continue; }
      const marker = bytes[p + 1];
      if (marker === 0xda || marker === 0xd9) break;
      if (marker === 0x00 || marker === 0xd8) { p += 2; continue; }
      const len = view.getUint16(p + 2, false);
      if (len < 2 || p + 2 + len > bytes.length) break;
      if ([0xe1, 0xeb, 0xed, 0xfe].includes(marker)) {
        chunks.push(bytes.slice(p + 4, p + 2 + len));
      }
      p += 2 + len;
    }
    return chunks;
  }

  // PNG: only inspect textual/provenance/EXIF chunks. Never inspect IDAT pixels.
  const isPng = bytes.length >= 8 && bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47;
  if (isPng) {
    let p = 8;
    while (p + 12 <= bytes.length) {
      const len = u32be(view, p);
      const type = ascii(bytes.slice(p + 4, p + 8));
      const dataStart = p + 8;
      const dataEnd = dataStart + len;
      if (dataEnd + 4 > bytes.length) break;
      if (['tEXt', 'iTXt', 'eXIf', 'caBX'].includes(type)) chunks.push(bytes.slice(dataStart, dataEnd));
      p = dataEnd + 4;
      if (type === 'IEND') break;
    }
    return chunks;
  }

  // WebP: inspect EXIF/XMP chunks, never VP8 pixel chunks.
  const isWebp = bytes.length >= 12 && ascii(bytes.slice(0, 4)) === 'RIFF' && ascii(bytes.slice(8, 12)) === 'WEBP';
  if (isWebp) {
    let p = 12;
    while (p + 8 <= bytes.length) {
      const type = ascii(bytes.slice(p, p + 4));
      const len = u32le(view, p + 4);
      const start = p + 8;
      const end = Math.min(start + len, bytes.length);
      if (['EXIF', 'XMP '].includes(type)) chunks.push(bytes.slice(start, end));
      p = start + len + (len % 2);
    }
    return chunks;
  }

  // MP4/other containers: scan only the downloaded header range for metadata text.
  // This is byte/string provenance inspection; no codec or pixel decoding occurs.
  if (/video|mp4|quicktime/i.test(contentType)) chunks.push(bytes);
  return chunks;
}

function decodeMetadata(chunks) {
  const decoder = new TextDecoder('utf-8', { fatal: false });
  return chunks.map((chunk) => `${decoder.decode(chunk)}\n${ascii(chunk)}`).join('\n').slice(0, 8 * 1024 * 1024);
}

function analyzeMetadataText(text, sensitivity) {
  const level = Math.max(1, Math.min(5, Number(sensitivity) || 3));
  for (const signal of SIGNALS) {
    if (signal.level > level) continue;
    for (const pattern of signal.patterns) {
      const match = text.match(pattern);
      if (match) return { match: true, confidence: signal.confidence, reason: signal.reason, marker: match[0].slice(0, 120) };
    }
  }
  return { match: false };
}

async function scanUrl(url, sensitivity) {
  const key = `${sensitivity}:${url}`;
  if (cache.has(key)) return cache.get(key);

  let result = { match: false };
  try {
    const response = await fetch(url, {
      method: 'GET',
      credentials: 'omit',
      cache: 'force-cache',
      headers: { Range: `bytes=0-${MAX_SCAN_BYTES - 1}` }
    });
    if (!response.ok && response.status !== 206) throw new Error(`HTTP ${response.status}`);

    const buffer = await response.arrayBuffer();
    const chunks = metadataSegments(buffer, response.headers.get('content-type') || '');
    if (chunks.length) result = analyzeMetadataText(decodeMetadata(chunks), sensitivity);
  } catch {
    result = { match: false, unavailable: true };
  }

  remember(key, result);
  return result;
}

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message?.type !== 'NO_AI_FEED_SCAN_METADATA') return;

  (async () => {
    const urls = Array.isArray(message.urls) ? message.urls.slice(0, 3) : [];
    for (const url of urls) {
      const result = await scanUrl(url, message.sensitivity);
      if (result.match) {
        sendResponse(result);
        return;
      }
    }
    sendResponse({ match: false });
  })();

  return true;
});
